### ISSUE TITLE
auth_token not set

### ISSUE THREAD

**Issue by evanrooijen** [eddiemoore/angular-spotify#18]
Hi, Im following your example but my auth token is not set so all future request return 401,
What can i do?

**Comment by eddiemoore** [comment]
Have you logged in first?
```javascript
Spotify.login()
```

**Comment by djgadd** [comment]
@eddiemoore I just ran into a similar (if not the same) issue, it looks like the provider method SpotifyProvider.setAuthToken() sets the property settings settings.accessToken which is never referenced. All of the auth requests make a reference to this.authToken, which is set by the factory method Spotify.setAuthToken(), should be a pretty easy fix.

@evanrooijen If you're using SpotifyProvider.setAuthToken() to set your token try using Spotify.setAuthToken() instead, it worked for me.

Hope that helps.

**Comment by eddiemoore** [comment]
@evanrooijen @djgadd Can you please update to the latest version of angular-spotify **v0.13.0** and try this again. The problem should now be fixed. Let me know if you run into any other problems.

**Comment by djgadd** [comment]
Thanks @eddiemoore, just had a quick look now and I'm still getting 401s when using SpotifyProvider.setAuthToken(), Spotify.setAuthToken() does work however. Haven't had chance to look at the code changes so can't give you much insight, sorry!

**Comment by eddiemoore** [comment]
I found the issue. Fixes in #20

**Comment by djgadd** [comment]
Yep, that's got it, thanks @eddiemoore

**Comment by eddiemoore** [comment]
Please update to v0.14.0
